image:
  repository: lenthenum/um-frontend
  tag: 0.0.1
apiUrl: "http://localhost:8002"
replicaCount: 2
probes:
  liveness:
    initialDelaySeconds: 15
    periodSeconds: 20
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10