image:
  repository: lenthenum/um-frontend
apiUrl: ""
replicaCount: 2
probes:
  liveness:
    initialDelaySeconds: 15
    periodSeconds: 20
  readiness:
    initialDelaySeconds: 5
    periodSeconds: 10