apiVersion: v1
kind: ConfigMap
metadata:
  name: grafana-loki-datasource
  namespace: grafana
  labels:
    grafana_datasource: "3"
    app.kubernetes.io/part-of: loki-stack
data:
  01-datasource.yaml: |-
    apiVersion: 1
    datasources:
    - name: Loki
      type: loki
      url: http://loki-stack-app.loki.svc.cluster.local:3100
      isDefault: true
      editable: true
      jsonData:
        maxLines: 1000
      uid: "custom-loki-datasource"
      jsonData:
        derivedFields:
          - datasourceUid: jaeger-datasource
            matcherRegex: '"trace_id":"(?P<value>[^"]+)"'
            name: TraceID
            url: '$${__value.raw}'
    - name: Jaeger
      type: jaeger
      uid: jaeger-datasource
      url: http://jaeger-query.jaeger.svc.cluster.local:16686
      access: proxy