apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cd-root-app
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  revisionHistoryLimit: 4
  source:
    path: cd-root
    repoURL: https://github.com/lenthenum/user-management.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      selfHeal: true
      prune: true