apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: db-credentials
  namespace: backend
spec:
  encryptedData:
    postgres-password: AgCFE9x43W5HtoTVbHvZWShl+e1F4UuJ5BBpxfiQfvRObbGg5YTz4Dl4AQi5GYRVvTPbmVD6qltIuG9WfvNT17DRvM0bgQf7D2BjYYOmQYnfLkxTUD+ClQBLqlWtzrGiDgv7Yp10ZsMf3jetpn369g7DP39h+Es2O1veu9gjFYFDX8WmH15Tg+0U91XzeOuj6bG1QrO0P1dQj+MHENEJ4Eq6ouUf/z5LJvVMasjiVrZvA6vw2yPZl4LDe5VO9P4ue3sIShqWtvDsgmF3POes0L3Jc8Musg+nK6Zi1NInel0oVGR8CGgxekqTftl+SXfsS/e3yySbSRF3HhhSWmhYWXvBxdUSg1pzN3a+YCkdYMrGmBoiwFmW/2591yVCdNREQDdkFxUU1QAf4Gb/aaLQm2XaDZJ2+cimgvfzKdaIDXF8lMgMJ6CDwxEiqm7xqylvNZuT28NHDHTiP/1EsFWQ9uhO4CnmCE1cDzPs0xFkqtdJ2JNXpaCmGrYQkuLYfVbE0txXMUwFGxjEOKDieQ3Y8GQsipssJTHuR0J/yWhwDz+nN+ZgDyx/vx0VO/YwRgSXO7u3rKK08k7O4kFxYQXyRlIHiXbZvk5TRyozUgN22SnD75gheEUsmJ/HikSrpE2RsvnVZmV2Gbj7Y+JUWG05jD5qVvai41E4yOyCLvBl0jGC0Z+NYAvycDyVLMkeBNx5TkbDpMQGI6/0wxAliUeQzI37Br877w==
  template:
    metadata:
      name: db-credentials
      namespace: backend
    type: Opaque
