apiVersion: v1
kind: Service
metadata:
  name: um-frontend-service
  namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  selector:
    app: um-frontend
  ports:
  - protocol: TCP
    port: 3000
    targetPort: 3000
  
---
apiVersion: v1
kind: Service
metadata:
  name: um-backend-alias
  namespace: {{ .Release.Namespace }}
spec:
  type: ExternalName
  externalName: um-backend.backend-ns.svc.cluster.local
  ports:
  - port: 8000