apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: um-unified-ingress
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/upstream-vhost: "um-frontend-service.frontend.svc.cluster.local"
spec:
  rules:
  - http:
      paths:
      - path: /api/go
        pathType: Prefix
        backend:
          service:
            name: um-backend-service
            port:
              number: 8000
      - path: /
        pathType: Prefix
        backend:
          service:
            name: um-frontend-bridge
            port:
              number: 80