apiVersion: v1
kind: Service
metadata:
  name: um-backend-service
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    app: um-backend
  ports:
  - protocol: TCP
    port: 8000
    targetPort: 8000