apiVersion: v2
name: loki
description: A wrapper chart for Loki Stack
version: 1.0.0
appVersion: "1.0.0"

dependencies:
  - name: loki-stack
    version: 2.9.10
    repository: https://grafana.github.io/helm-charts